import test from 'node:test';
import assert from 'node:assert/strict';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { runGC, checkHealth, runRecovery } from '../scripts/build-dag.mjs';

const rootDir = process.cwd();
const nlmDir = path.join(rootDir, '.nlm_pack');
const gensDir = path.join(nlmDir, 'generations');
const pointerFile = path.join(nlmDir, 'current_generation.json');
const docsFile = path.join(rootDir, 'docs', 'KB_SYNC_DAG.md');

// Helper to create a valid generation directory
function createMockGen(genId, sha = 'sha256:0000000000000000000000000000000000000000000000000000000000000000') {
  const dir = path.join(gensDir, genId);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'dag.json'), JSON.stringify({
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    version: '2.0.0',
    metadata: {
      content_hash: sha,
      created_at: new Date().toISOString(),
      source_file_count: 1,
      total_nodes: 1,
      total_edges: 0,
      cycles_count: 0,
      generation_id: genId
    },
    nodes: [{ id: 'node:file:readme.md', node_type: 'file', label: 'readme.md', path: 'readme.md', status: 'valid', target_kind: 'file', tags: [] }],
    edges: []
  }, null, 2));

  fs.writeFileSync(path.join(dir, 'adjacency.json'), JSON.stringify({
    version: '2.0.0',
    forward: { 'node:file:readme.md': [] },
    reverse: { 'node:file:readme.md': [] }
  }, null, 2));

  const docText = `<!-- AUTO-GENERATED BY KB-SYNC DAG BUILDER - DO NOT EDIT MANUALLY -->\n# KB-Sync Graph\nGen: ${genId}\n`;
  fs.writeFileSync(path.join(dir, 'KB_SYNC_DAG.md'), docText);
  fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify({ generation_id: genId, sha256: sha }, null, 2));
  return { dir, docText };
}

// 1. L12: Determinism test
test('L12: Determinism test', () => {
  // Run build twice
  execSync('npm run kb:dag', { cwd: rootDir, encoding: 'utf8' });
  const ptr1 = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  const genDir1 = path.join(gensDir, ptr1.active_generation);
  const dag1 = JSON.parse(fs.readFileSync(path.join(genDir1, 'dag.json'), 'utf8'));
  const adj1 = JSON.parse(fs.readFileSync(path.join(genDir1, 'adjacency.json'), 'utf8'));

  execSync('npm run kb:dag', { cwd: rootDir, encoding: 'utf8' });
  const ptr2 = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  const genDir2 = path.join(gensDir, ptr2.active_generation);
  const dag2 = JSON.parse(fs.readFileSync(path.join(genDir2, 'dag.json'), 'utf8'));
  const adj2 = JSON.parse(fs.readFileSync(path.join(genDir2, 'adjacency.json'), 'utf8'));

  assert.equal(dag1.metadata.content_hash, dag2.metadata.content_hash, 'content_hash must be bit-identical');
  assert.deepEqual(dag1.nodes, dag2.nodes, 'DAG nodes must be identical');
  assert.deepEqual(dag1.edges, dag2.edges, 'DAG edges must be identical');
  assert.deepEqual(adj1, adj2, 'Adjacency structures must be identical');
});

// 2. L35: Read-Only Check test
test('L35: Read-Only Check test', () => {
  // Ensure workspace is healthy first
  execSync('npm run kb:dag', { cwd: rootDir, encoding: 'utf8' });

  const getSnapshot = () => {
    const files = [];
    const walk = (d) => {
      for (const item of fs.readdirSync(d)) {
        const full = path.join(d, item);
        const stat = fs.statSync(full);
        if (stat.isDirectory()) walk(full);
        else files.push({ path: full, mtimeMs: stat.mtimeMs, size: stat.size });
      }
    };
    if (fs.existsSync(nlmDir)) walk(nlmDir);
    if (fs.existsSync(docsFile)) {
      const s = fs.statSync(docsFile);
      files.push({ path: docsFile, mtimeMs: s.mtimeMs, size: s.size });
    }
    return files;
  };

  const snapBefore = getSnapshot();
  const output = execSync('npm run kb:dag:check', { cwd: rootDir, encoding: 'utf8' });
  assert.ok(output.includes('[OK] KBSync DAG Health Check PASS'), 'Check output should indicate PASS');
  const snapAfter = getSnapshot();

  assert.equal(snapBefore.length, snapAfter.length, 'File count should not change');
  for (let i = 0; i < snapBefore.length; i++) {
    assert.equal(snapBefore[i].path, snapAfter[i].path);
    assert.equal(snapBefore[i].mtimeMs, snapAfter[i].mtimeMs, `File ${snapBefore[i].path} should not be modified`);
    assert.equal(snapBefore[i].size, snapAfter[i].size);
  }
});

// 3. L58: JSON Schema Validation test
test('L58: JSON Schema Validation test', () => {
  execSync('npm run kb:dag', { cwd: rootDir, encoding: 'utf8' });
  const ptr = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  const genDir = path.join(gensDir, ptr.active_generation);

  const dagSchema = JSON.parse(fs.readFileSync(path.join(rootDir, 'kb-sync', 'schemas', 'dag.schema.v2.json'), 'utf8'));
  const adjSchema = JSON.parse(fs.readFileSync(path.join(rootDir, 'kb-sync', 'schemas', 'adjacency.schema.v2.json'), 'utf8'));

  const dag = JSON.parse(fs.readFileSync(path.join(genDir, 'dag.json'), 'utf8'));
  const adj = JSON.parse(fs.readFileSync(path.join(genDir, 'adjacency.json'), 'utf8'));

  // Validate DAG against Schema rules
  assert.equal(dag.$schema, dagSchema.properties.$schema ? dag.$schema : 'https://json-schema.org/draft/2020-12/schema');
  assert.equal(dag.version, dagSchema.properties.version.const);
  assert.ok(dag.metadata, 'DAG metadata must exist');
  assert.ok(/^sha256:[a-f0-9]{64}$/.test(dag.metadata.content_hash), 'content_hash must match sha256 pattern');
  assert.ok(typeof dag.metadata.created_at === 'string');
  assert.ok(Number.isInteger(dag.metadata.source_file_count) && dag.metadata.source_file_count >= 0);
  assert.ok(Number.isInteger(dag.metadata.total_nodes) && dag.metadata.total_nodes >= 0);
  assert.ok(Number.isInteger(dag.metadata.total_edges) && dag.metadata.total_edges >= 0);
  assert.ok(Number.isInteger(dag.metadata.cycles_count) && dag.metadata.cycles_count >= 0);
  assert.ok(typeof dag.metadata.generation_id === 'string');

  const validNodeTypes = ['file', 'chunk', 'dangling'];
  const validNodeStatuses = ['valid', 'missing', 'stale'];
  const validTargetKinds = ['file', 'chunk', 'external'];

  const nodeIds = new Set();
  for (const node of dag.nodes) {
    assert.ok(node.id && typeof node.id === 'string');
    assert.ok(!nodeIds.has(node.id), `Node ID ${node.id} must be unique`);
    nodeIds.add(node.id);
    assert.ok(validNodeTypes.includes(node.node_type), `Invalid node_type: ${node.node_type}`);
    assert.ok(typeof node.label === 'string');
    assert.ok(typeof node.path === 'string');
    assert.ok(validNodeStatuses.includes(node.status), `Invalid status: ${node.status}`);
    assert.ok(validTargetKinds.includes(node.target_kind), `Invalid target_kind: ${node.target_kind}`);
    assert.ok(Array.isArray(node.tags));
  }

  const validRelations = ['contains', 'wikilink', 'mdlink', 'mention'];
  const edgeIds = new Set();
  for (const edge of dag.edges) {
    assert.ok(edge.id && typeof edge.id === 'string');
    assert.ok(!edgeIds.has(edge.id), `Edge ID ${edge.id} must be unique`);
    edgeIds.add(edge.id);
    assert.ok(typeof edge.source === 'string');
    assert.ok(typeof edge.target === 'string');
    assert.ok(validRelations.includes(edge.relation), `Invalid relation: ${edge.relation}`);
  }

  // Validate Adjacency against Schema rules & 100% coverage
  assert.equal(adj.version, adjSchema.properties.version.const);
  assert.ok(adj.forward && typeof adj.forward === 'object');
  assert.ok(adj.reverse && typeof adj.reverse === 'object');

  for (const nid of nodeIds) {
    assert.ok(Object.prototype.hasOwnProperty.call(adj.forward, nid), `Adjacency forward map missing key for node: ${nid}`);
    assert.ok(Object.prototype.hasOwnProperty.call(adj.reverse, nid), `Adjacency reverse map missing key for node: ${nid}`);
    assert.ok(Array.isArray(adj.forward[nid]));
    assert.ok(Array.isArray(adj.reverse[nid]));
  }
});

// 4. L80: Atomic Rollback & State Validation test
test('L80: Atomic Rollback & State Validation test', () => {
  // Ensure valid build first
  execSync('npm run kb:dag', { cwd: rootDir, encoding: 'utf8' });
  const initialPtr = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));

  // Simulate crash during pointer swap by leaving a partial .tmp file
  const tmpPtr = `${pointerFile}.tmp`;
  fs.writeFileSync(tmpPtr, JSON.stringify({ active_generation: 'corrupt_tmp_gen', sha256: 'sha256:0000' }));

  // Pointer file itself remains intact
  const currentPtr = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  assert.equal(currentPtr.active_generation, initialPtr.active_generation, 'Pointer file must remain untouched');

  // Check health passes because active pointer & docs are intact
  const health = checkHealth();
  assert.ok(health.healthy, 'Health check should pass despite leftover .tmp file');

  // Cleanup .tmp file
  if (fs.existsSync(tmpPtr)) fs.unlinkSync(tmpPtr);
});

// 5. L92: Self-Healing Forward Mismatch test
test('L92: Self-Healing Forward Mismatch test', () => {
  // Create Gen 1 and make it active
  const gen1 = '20260808_100000_11111111';
  const mock1 = createMockGen(gen1);
  fs.writeFileSync(pointerFile, JSON.stringify({ active_generation: gen1, sha256: 'sha256:1111' }, null, 2));
  fs.writeFileSync(docsFile, mock1.docText);

  // Create Gen 2 (newest)
  const gen2 = '20260808_110000_22222222';
  const mock2 = createMockGen(gen2);

  // Simulate crash between Step 2 (doc rename to Gen 2) and Step 3 (pointer swap):
  // docs/KB_SYNC_DAG.md has Gen 2 content, but pointer still points to Gen 1
  fs.writeFileSync(docsFile, mock2.docText);

  // Health check should flag mismatch between docs/KB_SYNC_DAG.md and Gen 1's doc
  const healthBefore = checkHealth();
  assert.equal(healthBefore.healthy, false, 'Health check must flag doc-vs-pointer mismatch');

  // Run recovery scan
  const recovered = runRecovery();
  assert.ok(recovered, 'Recovery should succeed');

  // Assert recovery adopted newest valid generation (Gen 2)
  const ptrAfter = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  assert.equal(ptrAfter.active_generation, gen2, 'Recovery should adopt newest valid generation (Gen 2)');
  assert.equal(fs.readFileSync(docsFile, 'utf8'), mock2.docText, 'docs/KB_SYNC_DAG.md should be updated to Gen 2 doc');

  // Health check should now pass
  const healthAfter = checkHealth();
  assert.ok(healthAfter.healthy, 'Health check must pass after recovery');
});

// 6. L110: Recovery & Self-Healing test
test('L110: Recovery & Self-Healing test', () => {
  // Ensure a valid generation exists
  const genId = '20260808_120000_33333333';
  const mock = createMockGen(genId);

  // Delete pointer file & corrupt docs file
  if (fs.existsSync(pointerFile)) fs.unlinkSync(pointerFile);
  fs.writeFileSync(docsFile, 'CORRUPT_INVALID_DOC_CONTENT');

  // Run recovery CLI
  const recoverOutput = execSync('npm run kb:dag:recover', { cwd: rootDir, encoding: 'utf8' });
  assert.ok(recoverOutput.includes('[Recovery] Successfully recovered'), 'Recovery output should signal success');

  // Verify pointer restored and docs healed
  assert.ok(fs.existsSync(pointerFile), 'Pointer file should be restored');
  const ptr = JSON.parse(fs.readFileSync(pointerFile, 'utf8'));
  assert.equal(ptr.active_generation, genId, 'Active generation should point to restored valid generation');
  assert.equal(fs.readFileSync(docsFile, 'utf8'), mock.docText, 'docs/KB_SYNC_DAG.md should be healed');

  const checkOutput = execSync('npm run kb:dag:check', { cwd: rootDir, encoding: 'utf8' });
  assert.ok(checkOutput.includes('[OK] KBSync DAG Health Check PASS'));
});

// 7. L135: GC Retention with Stale Active Pointer test
test('L135: GC Retention with Stale Active Pointer test', () => {
  // Clear existing mock generations for clean test isolation
  if (fs.existsSync(gensDir)) {
    for (const d of fs.readdirSync(gensDir)) {
      fs.rmSync(path.join(gensDir, d), { recursive: true, force: true });
    }
  }

  // Create 5 valid generations sorted by timestamp (Gen5 newest, Gen1 oldest)
  const g1 = '20260808_010000_00000001';
  const g2 = '20260808_020000_00000002';
  const g3 = '20260808_030000_00000003';
  const g4 = '20260808_040000_00000004';
  const g5 = '20260808_050000_00000005';

  createMockGen(g1);
  createMockGen(g2);
  createMockGen(g3);
  createMockGen(g4);
  createMockGen(g5);

  // Set active pointer to g1 (ranked 5th by recency, stale active pointer)
  fs.writeFileSync(pointerFile, JSON.stringify({ active_generation: g1, sha256: 'sha256:0000' }, null, 2));

  // Run Garbage Collection
  runGC();

  // Assert retained generations in gensDir:
  // Must retain 4 total: active (g1) + 3 top recent valid (g5, g4, g3)
  // Purged: g2
  const remaining = fs.readdirSync(gensDir).sort();
  assert.equal(remaining.length, 4, 'GC must retain exactly 4 generations');
  assert.deepEqual(remaining, [g1, g3, g4, g5], 'GC must retain active (g1) and top 3 recent valid (g5, g4, g3), purging g2');
});
